AllCops:
  Exclude:
    - "db/schema.rb"
    - "config/**/*"
    - "bin/**/*"
    - "vendor/bundle/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Lint/UnusedBlockArgument:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error
